### ISSUE TITLE
Some problem on Monitor.detect_iface()

### ISSUE THREAD

**Issue by u1Ys** [h-ohsaki/xpymon#1]
https://github.com/h-ohsaki/xpymon/blob/c6f1234d270f10de7c8c53f7918cbf8a763bc76d/xpymon#L143

In my environment, the output of **ip -oneline addr** is as follows, 

> $ ip -oneline addr
> 1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
> 1: lo    inet6 ::1/128 scope host \       valid_lft forever preferred_lft forever
> 3: wlp2s0    inet 192.168.10.108/24 brd 192.168.10.255 scope global wlp2s0\       valid_lft forever preferred_lft forever
> 3: wlp2s0    inet6 fe80::d66d:6dff:fe62:f070/64 scope link \       valid_lft forever preferred_lft forever

and the second *lo* matches. Therefore, I changed it as follows and finally it worked well.
```python
                                       ignore=r'127.0.0.1|::1/128')
```

**Comment by h-ohsaki** [comment]
Many thanks.  Your patch is adopted in version 1.2.
